//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Display_7_Segmentos_XYLO_TB(

	//////////// CLOCK //////////
	
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0
	
);



//=======================================================
//  REG/WIRE declarations
//=======================================================


//=======================================================
//  Structural coding
//=======================================================

Display_7_Segmentos_XYLO Display_7_Segmentos_XYLO_0 (.a(SW[17]),.b(SW[16]),.c(SW[15]),.d(SW[14]),.s0(HEX0));


endmodule
